baseURL = "https://gitfoto.com/"
title = "信心花舍"
author = "He Xinyu"
copyright = "Copyright © 2019–2021"
languageCode = "en"
DefaultContentLanguage = "en"
hasCJKLanguage=true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = "Pilgrim"
googleAnalytics = "UA-FAKE"
theme = "hugo-theme-tokiwa"

[markup.goldmark.renderer]
unsafe= true

[params]
description = """
Tokiwa-iro is the theme color of this site.
"""
favicon = "img/favicon-32x32.png"
math = true # for introducing $KaTEX$
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = true
bannerFont = "fonts/exampleFont"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[social]
github="http://github.com/PilgrimS"
wechat="Gravity_HE"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"
